### ISSUE TITLE
Thumbnail is cropped

### ISSUE THREAD

**Issue by laurmaedje** [AnsgarLichter/light-cv#1]
The bottom margin looks wrong in the thumbnail, but it's actually fine in the template!

**Comment by AnsgarLichter** [comment]
Thanks for spotting this difference.

I fixed this issue with [this commit](https://github.com/AnsgarLichter/light-cv/commit/e85b7de963a42426e39460fbf6a9f010fa7bcf7d).

I opened a PR in typst's packages repository: [https://github.com/typst/packages/pull/617](https://github.com/typst/packages/pull/617)
